// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw2BvMzQrjkG5mY0xCoLPPr78MoUHJycg',
    appId: '1:979268846924:web:5ca37f1c07c04e8564bbe9',
    messagingSenderId: '979268846924',
    projectId: 'presensi-50cb4',
    authDomain: 'presensi-50cb4.firebaseapp.com',
    storageBucket: 'presensi-50cb4.appspot.com',
    measurementId: 'G-ZEG19764HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVyPFQ3iYY98WNRueS0uvs-jZKy9snCLM',
    appId: '1:979268846924:android:1b18cf7a0ea937f664bbe9',
    messagingSenderId: '979268846924',
    projectId: 'presensi-50cb4',
    storageBucket: 'presensi-50cb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdIqzjhe3yh94pXA5eD-F4bDhfplkjrq4',
    appId: '1:979268846924:ios:f04cf8e306a854ed64bbe9',
    messagingSenderId: '979268846924',
    projectId: 'presensi-50cb4',
    storageBucket: 'presensi-50cb4.appspot.com',
    iosClientId: '979268846924-p807fll6aj4atptrrd26aip7vukv51as.apps.googleusercontent.com',
    iosBundleId: 'com.example.presensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdIqzjhe3yh94pXA5eD-F4bDhfplkjrq4',
    appId: '1:979268846924:ios:f04cf8e306a854ed64bbe9',
    messagingSenderId: '979268846924',
    projectId: 'presensi-50cb4',
    storageBucket: 'presensi-50cb4.appspot.com',
    iosClientId: '979268846924-p807fll6aj4atptrrd26aip7vukv51as.apps.googleusercontent.com',
    iosBundleId: 'com.example.presensi',
  );
}
